-- Load into staging table
-- SSMS>DB>Tasks>Import Flat File...>Set to nvarchar(255)

USE [ECS_Transform]
GO

INSERT INTO [stg_raw] (
      [quality_score]
      ,[view_certificate_1]
      ,[view_certificate_2]
      ,[Cupping Protocol and Descriptors]
      ,[View Green Analysis Details]
      ,[Request a Sample]
      ,[Species]
      ,[Owner]
      ,[Country of Origin]
      ,[Farm Name]
      ,[Lot Number]
      ,[Mill]
      ,[ICO Number]
      ,[Company]
      ,[Altitude]
      ,[Region]
      ,[Producer]
      ,[Number of Bags]
      ,[Bag Weight]
      ,[In-Country Partner]
      ,[Harvest Year]
      ,[Grading Date]
      ,[Variety]
      ,[Status]
      ,[Processing Method]
      ,[NA]
      ,[Fragrance / Aroma]
      ,[Flavor]
      ,[Aftertaste]
      ,[Salt / Acid]
      ,[Bitter / Sweet]
      ,[Mouthfeel]
      ,[NA2]
      ,[Uniform Cup]
      ,[Clean Cup]
      ,[Balance]
      ,[Cupper Points]
      ,[Total Cup Points]
      ,[NA3]
      ,[Moisture]
      ,[Category One Defects]
      ,[Quakers]
      ,[Color]
      ,[Category Two Defects]
      ,[NA4]
      ,[Expiration]
      ,[Certification Body]
      ,[Certification Address]
      ,[Certification Contact]
	  )
	  
SELECT 
      [quality_score]
      ,[view_certificate_1]
      ,[view_certificate_2]
      ,[Cupping_Protocol_and_Descriptors]
      ,[View_Green_Analysis_Details]
      ,[Request_a_Sample]
      ,[Species]
      ,[Owner]
      ,[Country_of_Origin]
      ,[Farm_Name]
      ,[Lot_Number]
      ,[Mill]
      ,[ICO_Number]
      ,[Company]
      ,[Altitude]
      ,[Region]
      ,[Producer]
      ,[Number_of_Bags]
      ,[Bag_Weight]
      ,[In_Country_Partner]
      ,[Harvest_Year]
      ,[Grading_Date]
      ,[Variety]
      ,[Status]
      ,[Processing_Method]
      ,[NA]
      ,[Fragrance_Aroma]
      ,[Flavor]
      ,[Aftertaste]
      ,[Salt_Acid]
      ,[Bitter_Sweet]
      ,[Mouthfeel]
      ,[NA2]
      ,[Uniform_Cup]
      ,[Clean_Cup]
      ,[Balance]
      ,[Cupper_Points]
      ,[Total_Cup_Points]
      ,[NA3]
      ,[Moisture]
      ,[Category_One_Defects]
      ,[Quakers]
      ,[Color]
      ,[Category_Two_Defects]
      ,[NA4]
      ,[Expiration]
      ,[Certification_Body]
      ,[Certification_Address]
      ,[Certification_Contact]
  FROM [ECS_Transform].[dbo].[cqidb_2020]